#!/usr/bin/env bash
# This script:
#  - Installs nginx on my web-01 server
#  - Makes Nginx listening on port 80
#  - When querying Nginx at its root / with a GET request (requesting a page) using curl,
#    it must return a page that contains the string Hello World!

apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html

new="listen [::]:80 default_server;\n\
        location /redirect_me {\n\
            return 301 https://www.google.com/;\n\
        }"
sed -i "s#listen \[::\]:80 default_server;#$new#" /etc/nginx/sites-available/default

service nginx restart
