#!/usr/bin/env bash
# This script makse sure that Nginx is running, and listening on port 80 of all the server’s active IPv4 IPs

result=$(grep -E "listen ([0-9]+) default_server;" "/etc/nginx/sites-available/default")
new_line="\tlisten 80 default_server;";

if [[ -z $result ]]
then
    sed -i "/server {/a\ $new_line" "/etc/nginx/sites-available/default";
else
    sed -i "s/$result/$new_line/" "/etc/nginx/sites-available/default";
fi

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart;
