#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.

cmd=$1

case $cmd in
    "start" )
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started";;

    "stop" )
        echo "manage_my_process stopped"
        kill "$(cat /var/run/my_process.pid)"
        rm -rf /var/run/my_process.pid;;
        
    "restart" )
        kill "$(cat /var/run/my_process.pid)"
        rm -rf /var/run/my_process.pid

        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        
        echo "manage_my_process restarted";;

        * )
            echo "Usage: manage_my_process {start|stop|restart}"
esac
