#!/usr/bin/env bash
# This script is displays numbers from 1 to 100.

n=1

while [ $n -le 100 ]
do
    if [ $((n%15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((n%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((n%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$n"
    fi
    ((n++))
done
