#!/usr/bin/env bash
# This script is displays the visitor IP along with the HTTP status code from the Apache log file.

FILE="apache-access.log"

awk -F " " '{print $1 " " $9}' $FILE | sort | uniq -c | sort -r